/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Paciente;

/**
 *
 * @author Windows 10
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFormularioDeDatos = new javax.swing.JLabel();
        lblInformacionPaciente = new javax.swing.JLabel();
        lblNombrePaciente = new javax.swing.JLabel();
        lblIdentificacion = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblEnfermedad = new javax.swing.JLabel();
        cmbEnfermedadPaciente = new javax.swing.JComboBox<>();
        txtCedulaPaciente = new javax.swing.JTextField();
        txtEdadPaciente = new javax.swing.JTextField();
        txtNombrePaciente = new javax.swing.JTextField();
        btnVerificarEdad = new javax.swing.JButton();
        lblVerificarEdad = new javax.swing.JLabel();
        btnCalcularIMC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFormularioDeDatos.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblFormularioDeDatos.setForeground(new java.awt.Color(255, 0, 0));
        lblFormularioDeDatos.setText("Formulario De Datos");
        lblFormularioDeDatos.setToolTipText("");

        lblInformacionPaciente.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblInformacionPaciente.setText("Informacion Paciente");

        lblNombrePaciente.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblNombrePaciente.setText("Nombre del paciente:");

        lblIdentificacion.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblIdentificacion.setText("Identificacion:");

        lblEdad.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblEdad.setText("Edad:");

        lblEnfermedad.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblEnfermedad.setText("Enfermedad");

        cmbEnfermedadPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gripa leve", "Enfermedad viral", "Alergia", "Anemia", "Diarrea" }));
        cmbEnfermedadPaciente.setToolTipText("");
        cmbEnfermedadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEnfermedadPacienteActionPerformed(evt);
            }
        });

        txtCedulaPaciente.setText("Ingrese su identificacion aqui");

        txtEdadPaciente.setText("Ingrese su edad aqui");

        txtNombrePaciente.setText("Ingrese su nombre aqui");

        btnVerificarEdad.setText("Verifica Tipo paciente ");
        btnVerificarEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarEdadActionPerformed(evt);
            }
        });

        lblVerificarEdad.setText("_");

        btnCalcularIMC.setText("Calcular IMC");
        btnCalcularIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularIMCActionPerformed(evt);
            }
        });

        jLabel1.setText("peso ideal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFormularioDeDatos)
                .addGap(146, 146, 146))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnCalcularIMC)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInformacionPaciente)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEnfermedad)
                                .addGap(18, 18, 18)
                                .addComponent(cmbEnfermedadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIdentificacion)
                                .addGap(18, 18, 18)
                                .addComponent(txtCedulaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEdad)
                                .addGap(32, 32, 32)
                                .addComponent(txtEdadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombrePaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnVerificarEdad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblVerificarEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblFormularioDeDatos)
                .addGap(18, 18, 18)
                .addComponent(lblInformacionPaciente)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePaciente)
                    .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedulaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdentificacion))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdad)
                    .addComponent(txtEdadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnfermedad)
                    .addComponent(cmbEnfermedadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerificarEdad)
                    .addComponent(lblVerificarEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularIMC)
                    .addComponent(jLabel1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private Paciente objetoPaciente;
    private void cmbEnfermedadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEnfermedadPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEnfermedadPacienteActionPerformed

    private void btnVerificarEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarEdadActionPerformed
        this.objetoPaciente = new Paciente();
        this.objetoPaciente.setNombre(this.txtNombrePaciente.getText());
        this.objetoPaciente.setCc(Long.parseLong(this.txtCedulaPaciente.getText()));
        this.objetoPaciente.setEdad(Integer.parseInt(this.txtEdadPaciente.getSelectedText()));
        this.objetoPaciente.setEnfermedadPpal(this.cmbEnfermedadPaciente.getSelectedItem().toString());
        this.lblVerificarEdad.setText(this.objetoPaciente.verificarTipoPersonaEdad());
    }//GEN-LAST:event_btnVerificarEdadActionPerformed

    private void btnCalcularIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularIMCActionPerformed
        this.objetoPaciente = new Paciente();
        

    }//GEN-LAST:event_btnCalcularIMCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularIMC;
    private javax.swing.JButton btnVerificarEdad;
    private javax.swing.JComboBox<String> cmbEnfermedadPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEnfermedad;
    private javax.swing.JLabel lblFormularioDeDatos;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblInformacionPaciente;
    private javax.swing.JLabel lblNombrePaciente;
    private javax.swing.JLabel lblVerificarEdad;
    private javax.swing.JTextField txtCedulaPaciente;
    private javax.swing.JTextField txtEdadPaciente;
    private javax.swing.JTextField txtNombrePaciente;
    // End of variables declaration//GEN-END:variables

 
    

        

    
}

/*package diangosticomedicoimc;

import Vista.Vista;

public class DiangosticoMedicoIMC {

  
    public static void main(String[] args) {
  Vista vista = new Vista();
  vista.setVisible(true);
    }
    
}*/
